name: Deploy GitHub Pages with LFS

on:
  push:
    branches:
      - main  # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository, including LFS pointers
    - name: Checkout repository with LFS
      uses: actions/checkout@v3
      with:
        lfs: true  # Fetch LFS files

    # Step 2: Build or prepare your site if needed (optional)
    # If you just serve raw HTML/JS, skip this step

    # Step 3: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Root directory, adjust if needed